* Casual Dired
An opinionated [[https://github.com/magit/transient][Transient]]-based porcelain to support the casual usage of Emacs [[https://www.gnu.org/software/emacs/manual/html_node/emacs/Dired.html][Dired]].

/insert screen shot/

* Motivation
While highly functional, Dired has a steep learning curve as it relies on single-key bindings for many of its commands. Menus are a user interface (UI) affordance that offer users discoverability and recall that can lower Dired's learning curve. While menus are commonly associated with mouse-driven UI, the inclusion of Transient in Emacs core allows for building a keyboard-driven menu UI which many users prefer. Casual Dired endeavors to offer this.

** Goals
- To provide a keyboard-driven menu UI to Dired.
- To provide easy access to common file manager operations.

** Non-Goals
- Full coverage of all Dired commands. Casual Dired is not intended to be a power user tool.
- Strict adherence to default Dired keybindings. That said, most Dired keybindings are honored.
- Strict adherence to Dired command naming. While Casual Dired is mostly in alignment with Dired’s command naming, there are cases where it will make an opinionated change if the name is deemed too vague or idiomatic.
- UX Stability (for now). Given that Casual Dired is early in its life-cycle, expect changes to its user experience in terms of menu hierarchy and keybinding choices in future releases.

* Asks
As Casual Dired is new, we are looking for early adopters! Your [[https://github.com/kickingvegas/Casual/issues][feedback]] is welcome as it will likely impact Casual Dired's evolution, particularly with regards to UI.

* Install
If installed via ~list-packages~ then add this line to your Emacs initialization file.
#+begin_src elisp :lexical no
  (define-key dired-mode-map (kbd "C-o") 'casual-dired-tmenu)
#+end_src

If you use ~use-package~, here is the recipe for installing it.
#+begin_src elisp :lexical no
  (use-package casual-dired
    :ensure t
    :bind (:map dired-mode-map ("C-o" . 'casual-dired-tmenu)))
#+end_src

If you are installing by using a clone of this repository, then ensure that the directory holding ~casual.el~ is in your ~info-path~. Add the following lines to your Emacs initialization file.

#+begin_src elisp :lexical no
  (require 'casual-dired)
  (define-key dired-mode-map (kbd "C-o") 'casual-dired-tmenu)
#+end_src

Casual requires Emacs 29.1+.

* Usage
1. Invoke ~M-x dired~ to launch Dired.
2. When the point is in the Dired window, invoke ~C-o~ (or a binding of your choosing) to launch the Casual Dired menu.

* Common Menu Actions
Casual Dired is built using Transient menus and as such adopts much of its default behavior.

Each menu item has a /key/ and a /label/. The /key/ is what is typed by the user to select the menu item. A key can be prefixed with a meta (M-) or control (C-) key. Labels ending with a ~>~ character indicates that it will open another menu.

Dismissing a menu regardless of how deep you are in sub-menus can be done by entering ~q~. A menu can also be dismissed by entering ~C-g~, but this will return you to the parent menu.

If a mouse is available, a menu item can be selected by moving the mouse cursor over its label and pressing down button 1.

Pressing the ~?~ key will toggle help for all the menu items. Press the key of interest to get help for it.

Some menus have arguments (example ~--all~) which you can set. You can persist these settings by typing ~C-x C-s~.

When a Transient menu is raised, a prefix argument (~C-u~) can be entered before selecting a menu item.

** Menu item notation
The following conventions are used to denote menu items.

If the label ends with a ~›~, it is a sub-menu.

If the label ends with an ~…~, the command will prompt you for an input value.

* Development
For users who wish to help contribute to Casual Dired or personally customize it for their own usage, please read the [[docs/developer.org][developer documentation]].

* Sponsorship
If you enjoy using Casual Dired, consider making a modest financial contribution to help support its development and maintenance.

[[https://www.buymeacoffee.com/kickingvegas][file:docs/images/default-yellow.png]]

* Acknowledgments
A heartfelt thanks to all the contributors to Calc and Transit. Casual would not be possible without your efforts.
